name: CI/CD

on: [push]

jobs:
  builds:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
     
    - name: permission to gradle
      run: chmod +x gradlew
      
    - name: build with gradle
      run: ./gradlew build
      
